package tms.octopus.octopus_tms.base.invoice.model;


public enum InvoiceStatus {

    DRAFT,
    SENT,
    VIEWED,
    PARTIAL_PAID,
    PAID,
    OVERDUE,
    DISPUTED,
    CANCELLED,
    PENDING,
    REFUNDED,
    VOIDED,
    ARCHIVED,
    DELETED,
    UNPAID,
    PARTIAL_REFUNDED,
    PENDING_REFUND,
    PENDING_PAYMENT,
    PENDING_APPROVAL,
    PENDING_VERIFICATION,
    PENDING_REVIEW,
    PENDING_CONFIRMATION,
    PENDING_CANCELLATION,
    PENDING_DISPUTE,
    PENDING_RESOLUTION,
    PENDING_CREDIT,
    PENDING_DEBIT,

}
